parameters:
    oro_distribution.routing_loader.class:            Oro\Bundle\DistributionBundle\Routing\OroAutoLoader
    oro_distribution.package_manager.class:           Oro\Bundle\DistributionBundle\Manager\PackageManager

services:
    oro_distribution.routing_loader:
        class:                                        %oro_distribution.routing_loader.class%
        arguments:
            - "@file_locator"
            - "@kernel"
        tags:
            - { name: routing.loader }

    oro_distribution.package_manager:
        class: %oro_distribution.package_manager.class%