parameters:
    oro_distribution.routing_loader.class:            Oro\Bundle\DistributionBundle\Routing\OroAutoLoader
    oro_distribution.package_manager.class:           Oro\Bundle\DistributionBundle\Manager\PackageManager
    oro_distribution.composer.class:                  Composer\Composer
    oro_distribution.composer.io.class:               Composer\IO\BufferIO
    oro_distribution.composer.installer.class:        Composer\Installer

services:
    oro_distribution.routing_loader:
        class:                                        %oro_distribution.routing_loader.class%
        arguments:
            - "@file_locator"
            - "@kernel"
        tags:
            - { name: routing.loader }

    oro_distribution.package_manager:
        class: %oro_distribution.package_manager.class%
        arguments: [@oro_distribution.composer, @oro_distribution.composer.installer]

    oro_distribution.composer.io:
        class: %oro_distribution.composer.io.class%

    oro_distribution.composer.installer:
        class: %oro_distribution.composer.installer.class%
        public: false
        factory_class: Composer\Installer
        factory_method: create
        arguments: [@oro_distribution.composer.io, @oro_distribution.composer]

    oro_distribution.composer:
        class: %oro_distribution.composer.class%
        public: false
        factory_class: Composer\Factory
        factory_method: create
        arguments: [@oro_distribution.composer.io]

