parameters:
    oro_distribution.routing_loader.class:                 Oro\Bundle\DistributionBundle\Routing\OroAutoLoader
    oro_distribution.package_manager.class:                Oro\Bundle\DistributionBundle\Manager\PackageManager
    oro_distribution.script_runner.class:                  Oro\Bundle\DistributionBundle\Script\Runner
    oro_distribution.composer.class:                       Composer\Composer
    oro_distribution.composer.io.class:                    Composer\IO\BufferIO
    oro_distribution.composer.installer.class:             Composer\Installer
    oro_distribution.composer.installation_manager.class:  Composer\Installer\InstallationManager
    oro_distribution.composer_json:                        %kernel.root_dir%/../composer.json

    oro_user.manager.class:             Oro\Bundle\UserBundle\Entity\UserManager
    oro_user.entity.class:              Oro\Bundle\UserBundle\Entity\User
    oro_user.security.provider.class:   Oro\Bundle\UserBundle\Security\UserProvider
    kernel.listener.oro.access_denied.class: Oro\Bundle\DistributionBundle\Security\AccessDeniedHandler

services:
    oro_distribution.routing_loader:
        class:                                        %oro_distribution.routing_loader.class%
        arguments:
            - "@file_locator"
            - "@kernel"
        tags:
            - { name: routing.loader }

    oro_distribution.package_manager:
        class: %oro_distribution.package_manager.class%
        arguments:
          - @oro_distribution.composer
          - @oro_distribution.composer.installer
          - @oro_distribution.composer.io
          - @oro_distribution.script_runner
          - %oro_distribution.composer_json%

    oro_distribution.script_runner:
        class: %oro_distribution.script_runner.class%
        public: false
        arguments: [@oro_distribution.composer.installation_manager]

    oro_distribution.composer.io:
        class: %oro_distribution.composer.io.class%
        public: false

    oro_distribution.composer.installer:
        class: %oro_distribution.composer.installer.class%
        public: false
        factory_class: Composer\Installer
        factory_method: create
        arguments: [@oro_distribution.composer.io, @oro_distribution.composer]

    oro_distribution.composer:
        class: %oro_distribution.composer.class%
        factory_class: Composer\Factory
        factory_method: create
        arguments: [@oro_distribution.composer.io, %oro_distribution.composer_json%]

    oro_distribution.composer.installation_manager:
        class: %oro_distribution.composer.installation_manager.class%
        public: false
        factory_service: oro_distribution.composer
        factory_method: getInstallationManager


    oro_user.manager:
        class:                        %oro_user.manager.class%
        arguments:                    [%oro_user.entity.class%, "@doctrine.orm.entity_manager", "@security.encoder_factory"]

    oro_user.security.provider:
        class:                        %oro_user.security.provider.class%
        public:                       false
        arguments:                    ["@oro_user.manager"]

    kernel.listener.access_denied:
        class: %kernel.listener.oro.access_denied.class%
        arguments: ["@session", "@router", "@security.context"]
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException }